### PR TITLE
fix error for Docker API version

### PR DESCRIPTION
**Pull request by blabla1337**
Hi,

I was trying your awesome scripts and many thanks for this but it got stuck in the installation steps as it was trying to use Docker api version 1.40 and this was not supported. 

The fix was to pin the Docker api to 1.39 
```
export DOCKER_API_VERSION=1.39
```
I added it in the MakeFile and it works again.

Kind regards,
Glenn

### CODE REVIEW

**Comment by lucasteligioridis** [comment]
Oh really? Thats interesting. Nice find mate.

**Comment by lucasteligioridis** [comment]
What was the error if you dont mind me asking? What was presenting the error?

**Comment by blabla1337** [comment]
Hmm I don't have the error anymore on screen but it was failing because it tried to pull the needed images from k8s.io and it failed because of the docker api used was 1.40 and that version was not supported

**Comment by lucasteligioridis** [comment]
Yeah cool, thats what I was trying to ascertain, so the https://github.com/lucasteligioridis/raspbernetes/blob/master/raspbernetes/install/kubernetes.sh#L30 command was the issue?

**Comment by blabla1337** [comment]
Yes that's correct, it failed

**Comment by lucasteligioridis** [comment]
Cool, thanks for the prompt responses and details :)

**Review by lucasteligioridis — APPROVED** [review]

**Pull request merged**
