### PR TITLE
Fix mounts for non mmcblk devices

### PR DESCRIPTION
**Pull request by slm4996**
This should resolve issue #1

### CODE REVIEW

**Comment by lucasteligioridis** [comment]
Sorry for the delay on this PR.

I would prefer to just have a variable that would overwrite the existing disk name instead.

It feels cleaner, sure a little less automated but at least keeps it far more flexible and no need to have a lot of logic to try and determine the disk name automatically.

I find Makefile syntax to be quite ugly and unreadable, try to use it as an entry point and keep it simple.

What do you think?

**Comment by slm4996** [comment]
That is what this does already....?

**Comment by lucasteligioridis** [comment]
Well it would have 2 variables that would look like instead:

```
MNT_DEVICE_1 ?= /dev/mmcblk0p1
MNT_DEVICE_2 ?= /dev/mmcblk0p2
```

**Comment by lucasteligioridis** [comment]
Going to close this PR if no further discussion is made on the above comment.

Just want to politely bump.

**Comment by lucasteligioridis** [comment]
Closing to inactivity.

**Pull request closed without merging**
